"""add isced levels table

Revision ID: 33b3ea625025
Revises: 468df1b5d178
Create Date: 2026-04-26 09:16:19.494146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b3ea625025'
down_revision: Union[str, Sequence[str], None] = '468df1b5d178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isced_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isced_levels_level'), 'isced_levels', ['level'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_isced_levels_level'), table_name='isced_levels')
    op.drop_table('isced_levels')
    # ### end Alembic commands ###
